### ISSUE TITLE
reviewdog this is not a pullRequest build

### ISSUE THREAD

**Issue by rpbaltazar** [reviewdog/action-brakeman#17]
I've tried to use this github action and I'm getting an error while running it:

```
reviewdog: this is not PullRequest build.
/usr/local/bundle/gems/brakeman-4.8.2/lib/brakeman.rb:415:in `write': Broken pipe @ io_write - <STDOUT> (Errno::EPIPE)
	from /usr/local/bundle/gems/brakeman-4.8.2/lib/brakeman.rb:415:in `puts'
	from /usr/local/bundle/gems/brakeman-4.8.2/lib/brakeman.rb:415:in `puts'
	from /usr/local/bundle/gems/brakeman-4.8.2/lib/brakeman.rb:415:in `block in write_report_to_formats'
	from /usr/local/bundle/gems/brakeman-4.8.2/lib/brakeman.rb:414:in `each'
	from /usr/local/bundle/gems/brakeman-4.8.2/lib/brakeman.rb:414:in `write_report_to_formats'
	from /usr/local/bundle/gems/brakeman-4.8.2/lib/brakeman.rb:384:in `scan'
	from /usr/local/bundle/gems/brakeman-4.8.2/lib/brakeman.rb:80:in `run'
	from /usr/local/bundle/gems/brakeman-4.8.2/lib/brakeman/commandline.rb:133:in `run_brakeman'
	from /usr/local/bundle/gems/brakeman-4.8.2/lib/brakeman/commandline.rb:118:in `regular_report'
	from /usr/local/bundle/gems/brakeman-4.8.2/lib/brakeman/commandline.rb:142:in `run_report'
	from /usr/local/bundle/gems/brakeman-4.8.2/lib/brakeman/commandline.rb:35:in `run'
	from /usr/local/bundle/gems/brakeman-4.8.2/lib/brakeman/commandline.rb:20:in `start'
	from /usr/local/bundle/gems/brakeman-4.8.2/bin/brakeman:10:in `<top (required)>'
	from /usr/local/bundle/bin/brakeman:23:in `load'
	from /usr/local/bundle/bin/brakeman:23:in `<main>'	
```

Not sure how to fix it

I found this ticket that seems related: https://github.com/reviewdog/reviewdog/issues/872 but there is not really an explanation on how to fix it and it seems related to Circle CI instead of github actions

**Comment by rpbaltazar** [comment]
This is actually caused by the same thing reported in https://github.com/reviewdog/action-rubocop/issues/37
Closing this issue, since for my use case, running explicitly on pull_request is fine.
